// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NX.Database;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace _NEXUS.Database.Migrations
{
    [DbContext(typeof(NXContext))]
    [Migration("20240913200017_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_NEXUS.Models.PedidosModel", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PEDIDO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<long>("CodigoPedido")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NR_PEDIDO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VL_QUANTIDADE");

                    b.Property<int>("ValorPedido")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VL_PEDIDO");

                    b.HasKey("IdPedido");

                    b.ToTable("TB_NX_PEDIDOS", (string)null);
                });

            modelBuilder.Entity("_NEXUS.Models.ProdutosModel", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PRODUTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_PRODUTO");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NM_MARCA");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NM_MODELO");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_PRODUTO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VL_QUANTIDADE");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_PRODUTO");

                    b.Property<int>("ValorProduto")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VL_PRODUTO");

                    b.HasKey("IdProduto");

                    b.ToTable("TB_NX_PRODUTOS", (string)null);
                });

            modelBuilder.Entity("_NEXUS.Models.UsuarioModel", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<long>("CPF")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NR_CPF");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_USUARIO");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<long>("telefone")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NR_TELEFONE");

                    b.HasKey("IdUsuario");

                    b.ToTable("TB_NX_USUARIOS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
